/**
 * @file    heater.h
 * @brief   Heater PWM driver (TIM3_CH1, PC6) public API.
 *
 * The heater drives a YJL3400A N-MOSFET (gate on PC6) that switches a 10 Ω
 * 5 W resistor across the system 5 V rail.  Output is a slow ~1 Hz PWM
 * generated by TIM3_CH1.  This header declares the entire public surface
 * required by Requirement 5 of the @c hardware-base-drivers spec.
 *
 * State model:
 *   - Uninitialised → every non-init API returns @ref DRV_ERR_NOT_INIT.
 *   - Normal        → @c Heater_SetDuty drives the comparator.
 *   - FaultLatched  → @c Heater_SetDuty refuses with @ref DRV_ERR_NOT_INIT
 *                     until @c Heater_ClearFault clears the latch.
 *
 * This header is intended to be included via the umbrella
 * @c "hardware.h" only — it relies on @ref Driver_Status, @c bool, and
 * @c HEATER_OVERHEAT_THRESHOLD_C being already in scope.
 *
 * Validates: Requirements 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 5.10, 8.6.
 */
#ifndef HEATER_H
#define HEATER_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialise TIM3_CH1 PWM output and self-correct the PWM frequency
 *        to ~1 Hz if CubeMX configured it outside [0.9, 1.1] Hz.
 *
 * Sequence:
 *   1. Compute current frequency from @c htim3.Init.Prescaler/Period using
 *      @c f = 240 MHz / ((PSC+1) * (ARR+1)).
 *   2. If @c f is outside [0.9, 1.1] Hz (or zero from a degenerate config),
 *      force @c PSC = 24000-1 and @c ARR = 10000-1 (yields 1 Hz).
 *   3. Set @c CCR1 = 0 and @c s_current_duty = 0.
 *   4. Call @c HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1).  Any non-OK status
 *      is propagated through @c Driver_MapHalStatus.
 *   5. Mark module initialised, clear fault latch, return @ref DRV_OK.
 */
Driver_Status Heater_Init(void);

/**
 * @brief Set the PWM duty cycle (0.0 .. 1.0).
 *
 * Negative values are clamped to 0; values > 1 are clamped to 1; @c NaN is
 * rejected with @ref DRV_ERR_PARAM.  When the module is not initialised or
 * the fault latch is set, @ref DRV_ERR_NOT_INIT is returned and no hardware
 * register is written.
 */
Driver_Status Heater_SetDuty(float duty);

/**
 * @brief Read back the most recently *applied* duty cycle.
 *
 * Returns @ref DRV_ERR_PARAM if @p duty is @c NULL,
 * @ref DRV_ERR_NOT_INIT if @c Heater_Init has not run yet.
 */
Driver_Status Heater_GetDuty(float *duty);

/**
 * @brief Immediately drive @c CCR1 to 0 and latch the fault flag.
 *
 * After this call, @c Heater_SetDuty refuses to drive the heater until
 * @c Heater_ClearFault is invoked.
 */
Driver_Status Heater_EmergencyStop(void);

/** @brief Clear the fault latch.  Hardware is *not* automatically resumed —
 *         the caller must explicitly @c Heater_SetDuty again. */
Driver_Status Heater_ClearFault(void);

/**
 * @brief Trip the emergency stop when the measured temperature exceeds the
 *        configured @ref HEATER_OVERHEAT_THRESHOLD_C threshold.
 *
 * @return @ref DRV_OK below the threshold, @ref DRV_ERR_PARAM at/above it
 *         (after @c Heater_EmergencyStop has been invoked internally).
 */
Driver_Status Heater_OverheatCheck(float temperature_c);

/** @brief Read-only query of the fault-latched flag.
 *         Returns @c false when the module is not initialised. */
bool          Heater_IsFaultLatched(void);

#ifdef __cplusplus
}
#endif

#endif /* HEATER_H */
